# Concatenación de DataFrames: concat y append (16/29)

In [1]:
import pandas as pd 
import numpy as np 


In [2]:
pd.options.display.float_format='{:.2f}'.format # Es para que los numeros solo tengan 2 decimales con pandas

In [3]:
np.set_printoptions(precision=2) # Es para que los numeros solo tengan 2 decimales con numpy

In [5]:
np.random.rand() # Crear numeros aleatorios con NUMPY entre 0 y 1

0.4793920815694628

In [7]:
np.random.randn() # Crear numeros aleatorios con NUMPY entre -1 y 1

0.08342498076610294

In [13]:
x1 = np.random.rand(2,5)*10  # Crear numeros aleatorios con NUMPY entre 0 a 1 multiplicado por 100 el valor aleatorio. Generando una matriz de 2 por 5
x1

array([[6.51, 4.45, 6.63, 4.6 , 9.36],
       [8.74, 6.19, 9.09, 7.4 , 7.8 ]])

In [11]:
x2 = np.random.rand(2,5)*-1 # Crear numeros aleatorios con NUMPY entre 0 a 1 multiplicado por -1 el valor aleatorio. Generando una matriz de 2 por 5
x2

array([[-0.09, -0.65, -0.12, -0.31, -0.05],
       [-0.08, -0.71, -0.85, -0.39, -0.58]])

In [14]:
np.concatenate([x1,x2]) # Concatenando las matrices x1 y x2

array([[ 6.51,  4.45,  6.63,  4.6 ,  9.36],
       [ 8.74,  6.19,  9.09,  7.4 ,  7.8 ],
       [-0.09, -0.65, -0.12, -0.31, -0.05],
       [-0.08, -0.71, -0.85, -0.39, -0.58]])

In [15]:
np.concatenate([x1,x2]).shape # Saber de que esta hecho las matrices en este caso summo 2 matrices de 2x5 quedando 4x5

(4, 5)

In [17]:
np.concatenate([x1,x2], axis = 1) # Junta ambas matrices pero ahora la x1 queda en una matriz y la x2 tambien quedando con 2 matrices con 10 columnas cada auna 

array([[ 6.51,  4.45,  6.63,  4.6 ,  9.36, -0.09, -0.65, -0.12, -0.31,
        -0.05],
       [ 8.74,  6.19,  9.09,  7.4 ,  7.8 , -0.08, -0.71, -0.85, -0.39,
        -0.58]])

In [18]:
np.concatenate([x1,x2], axis = 1).shape  # Junta ambas matrices pero ahora la x1 queda en una matriz y la x2 tambien quedando con 2 matrices con 10 columnas cada auna 

(2, 10)

In [20]:
s1 = pd.Series(x1[0], index = ['a','b','c','d','e']) # Creando 5 elementos en la serie con PANDAS
s1

a   6.51
b   4.45
c   6.63
d   4.60
e   9.36
dtype: float64

In [21]:
s2 = pd.Series(x2[0], index = ['c','d','e','f','g']) # Creando 5 elementos en la serie con PANDAS
s2

c   -0.09
d   -0.65
e   -0.12
f   -0.31
g   -0.05
dtype: float64

In [22]:
pd.concat([s1,s2]) # Concatenando las series con PANDAS y esto es a lo largo de las filas

a    6.51
b    4.45
c    6.63
d    4.60
e    9.36
c   -0.09
d   -0.65
e   -0.12
f   -0.31
g   -0.05
dtype: float64

In [29]:
pd.concat([s1,s2], axis=1) # Se concatenan y generan 2 columnas

0     1
a 6.51   NaN
b 4.45   NaN
c 6.63 -0.09
d 4.60 -0.65
e 9.36 -0.12
f  NaN -0.31
g  NaN -0.05

In [30]:
s1.reset_index(drop=True) # Esto es para resetear el indice y que no aparecezca las letras

0   6.51
1   4.45
2   6.63
3   4.60
4   9.36
dtype: float64

In [31]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1) # Se concatenan y generan 2 columnas pero borrando los indeces de letras y solo dejando el numero de la posicion

0     1
0 6.51 -0.09
1 4.45 -0.65
2 6.63 -0.12
3 4.60 -0.31
4 9.36 -0.05

In [33]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b']) #Creando una matriz de 2 columnas y 3 filas
df1

a    b
0 2.50 9.68
1 5.81 5.75
2 6.25 7.99

In [34]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index=[2,3,4]) #Creando una matriz de 2 columnas y 3 filas
df2

a     b
2 -0.82 -0.75
3 -0.02 -0.48
4 -0.60 -0.38

In [35]:
pd.concat([df1,df2]) # Concatenando dos dataframe

a     b
0  2.50  9.68
1  5.81  5.75
2  6.25  7.99
2 -0.82 -0.75
3 -0.02 -0.48
4 -0.60 -0.38

In [36]:
pd.concat([df1,df2], axis=1) 

a    b     a     b
0 2.50 9.68   NaN   NaN
1 5.81 5.75   NaN   NaN
2 6.25 7.99 -0.82 -0.75
3  NaN  NaN -0.02 -0.48
4  NaN  NaN -0.60 -0.38

In [42]:
pd.concat([df1,df2], axis=1, join='inner') # Se queda marcando una fila

a    b     a     b
2 6.25 7.99 -0.82 -0.75

In [46]:
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1) # Reseteando los indices y desaparenciendolos 

a    b     a     b
0 2.50 9.68 -0.82 -0.75
1 5.81 5.75 -0.02 -0.48
2 6.25 7.99 -0.60 -0.38

In [47]:
df1.reset_index(drop=True).T.append(df2.reset_index(drop=True).T).T #Si queremos que la append ocurra en el sentido de las columnas

a    b     a     b
0 2.50 9.68 -0.82 -0.75
1 5.81 5.75 -0.02 -0.48
2 6.25 7.99 -0.60 -0.38

In [49]:
df1.append(df2) # Se junta las matrices una debajo de la otra

a     b
0  2.50  9.68
1  5.81  5.75
2  6.25  7.99
2 -0.82 -0.75
3 -0.02 -0.48
4 -0.60 -0.38

In [50]:
df1.append(df2).append(df2) # Se junta las matrices una debajo de la otra

a     b
0  2.50  9.68
1  5.81  5.75
2  6.25  7.99
2 -0.82 -0.75
3 -0.02 -0.48
4 -0.60 -0.38
2 -0.82 -0.75
3 -0.02 -0.48
4 -0.60 -0.38

In [51]:
df1.T # Invertir donde estan las filas por las columnas y viceversa

0    1    2
a 2.50 5.81 6.25
b 9.68 5.75 7.99

In [52]:
df1.T.append(df2.T).T

a    b     a     b
0 2.50 9.68   NaN   NaN
1 5.81 5.75   NaN   NaN
2 6.25 7.99 -0.82 -0.75
3  NaN  NaN -0.02 -0.48
4  NaN  NaN -0.60 -0.38