# Ejercicios Video 2

In [24]:
import numpy as np
import pandas as pd


In [25]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [26]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [27]:
np.array([1,2,3,4,5]).shape

(5,)

In [28]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [29]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [30]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [31]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

# ejercicio video 3


In [32]:
pd.Series([10,9,8,7,6]) # Ordena hacia abajo con una columna de indexacion

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [33]:
sr = pd.Series([10,9,8,7,6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [34]:
sr.values # Muestra los valores

array([10,  9,  8,  7,  6], dtype=int64)

In [35]:
sr.index # Muestra la indexacion

RangeIndex(start=0, stop=5, step=1)

In [36]:
sr.shape # dimensionalidad del objeto (cantidad de elementos)

(5,)

In [37]:
sr[3] # seleccionar elemento

7

In [38]:
sr[[0,4,2]] # elementos por indice 0,4,2

0    10
4     6
2     8
dtype: int64

In [39]:
sr = pd.Series([10,9,8,7,6], index =['a','b','c','d','e']) # intercambiando el index de numero a letra
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [40]:
sr['c'] 

8

In [41]:
sr[['c','a']]  # llamada de multiples elementos

c     8
a    10
dtype: int64

In [42]:
sr['a':'c'] # Seleccionando un rango de elementos 

a    10
b     9
c     8
dtype: int64

In [43]:
{'CO':100,'MX':200,'AR':300,'CL':1500} # Diccionario

{'CO': 100, 'MX': 200, 'AR': 300, 'CL': 1500}

In [44]:
dict_data ={'CO':100,'MX':200,'AR':300,'CL':1500} # Diccionario
dict_data

{'CO': 100, 'MX': 200, 'AR': 300, 'CL': 1500}

In [45]:
dict_data.keys() # Muestra las llaves 

dict_keys(['CO', 'MX', 'AR', 'CL'])

In [47]:
dict_data['CL'] # Extrae los datos contenidos en la llave

1500

In [48]:
pd.Series(dict_data) # Transformacion de serie

CO     100
MX     200
AR     300
CL    1500
dtype: int64

In [49]:
pd.Series(dict_data, index=['CO','MX','PE']) # Creando serie nueva

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [50]:
np.nan # NaN es un objeto nulo que tambien puede cumplir operaciones matematicas

nan

In [51]:
np.nan + 10 # Cualquier variable numerica que tenga NaN siempre sera NaN (nula)

nan

In [53]:
sr = pd.Series(dict_data, index=['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [54]:
sr.isnull() # Para saber si los valores son nulos.

CO    False
MX    False
PE     True
dtype: bool

In [56]:
sr.notnull() # Para saber si los valores no son nulos

CO     True
MX     True
PE    False
dtype: bool

In [57]:
sr.isnull().any() #regresa un booleano indicandonos si existe (TRUE) o no existe (FALSE) algun nan

True

In [58]:
sr[sr.notnull()] # regresa los valores de la serie que “NO” son nulos.


CO    100.0
MX    200.0
dtype: float64